name: Bug Report
description: Report a bug or issue with the SFF Wheel Library app
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and fix the issue.

  - type: dropdown
    id: device
    attributes:
      label: Device Type
      description: What device are you using?
      options:
        - iPhone (Safari)
        - Android (Chrome)
        - Desktop (Chrome)
        - Desktop (Safari)
        - Desktop (Firefox)
        - iPad (Safari)
        - Other
    validations:
      required: true

  - type: dropdown
    id: pwa-status
    attributes:
      label: PWA Installation Status
      description: Are you using the installed PWA or the website in a browser?
      options:
        - Installed PWA (home screen app)
        - Browser (not installed)
        - Not sure
    validations:
      required: true

  - type: dropdown
    id: network
    attributes:
      label: Network Status
      description: Were you online or offline when the bug occurred?
      options:
        - Online (connected to internet)
        - Offline (no internet connection)
        - Intermittent connection
        - Not sure
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the bug in detail. What did you expect to happen vs. what actually happened?
      placeholder: |
        Example: "I selected the 'rhythm' environment filter and '57mm' size filter, but the app showed wheels that are 62mm instead of 57mm."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug? Please be as detailed as possible.
      placeholder: |
        1. Open the app
        2. Click on '...'
        3. Select '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "I expected the app to show only 57mm wheels when I selected that filter."
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How much does this bug affect your ability to use the app?
      options:
        - Critical (app is completely broken)
        - High (major feature doesn't work)
        - Medium (feature works but has issues)
        - Low (minor annoyance)
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem. You can drag and drop images here.
      placeholder: "Drag and drop images here, or click to upload."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here. Browser version, OS version, etc.
      placeholder: |
        - iOS version: 17.2
        - Safari version: 17.2
        - App installed: Yes
        - Last updated: 2 days ago

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting.
      options:
        - label: I have searched existing issues to make sure this isn't a duplicate
          required: true
        - label: I have provided clear steps to reproduce the bug
          required: true
        - label: I have included relevant screenshots or error messages (if applicable)
          required: false
